export const opponents = [
  {
    id: "giselle",
    name: "Giselle",
    portrait: "/opponents/giselle.png",
    personality: "Sharp strategist",
    dialogue: {
      intro: [
        "Let's see your opening preparation.",
        "I've analyzed your games. This should be instructive.",
        "A sharp battle ahead. I can feel it.",
        "Time to test your tactical vision.",
        "I won't give you a single free tempo.",
      ],
      playerMove: [
        "A principled move.",
        "Controlling the center. Good.",
        "That's a solid developing move.",
        "Interesting pawn structure choice.",
        "You're playing with purpose.",
        "A classical approach.",
        "Your piece placement is improving.",
        "I see your plan forming.",
      ],
      opponentMove: [
        "Let me improve my worst piece.",
        "Restricting your options.",
        "A prophylactic move.",
        "Targeting your weak squares.",
        "Developing with tempo.",
        "Centralizing my pieces.",
        "Preparing a pawn break.",
        "A subtle but important move.",
      ],
      capture: [
        "A necessary exchange.",
        "Simplifying favors me here.",
        "Material balance shifts.",
        "Trading into a better endgame.",
        "The position opens up.",
        "A calculated sacrifice.",
        "Removing a key defender.",
      ],
      check: [
        "Check. Your king needs safety.",
        "Forcing your response.",
        "A direct threat to the king.",
        "Your king is exposed now.",
        "Where will your king go?",
      ],
      playerWin: [
        "You have a clear advantage.",
        "Your position is dominant.",
        "I need to find counterplay.",
        "A strong initiative on your side.",
        "You're pressing well.",
      ],
      opponentWin: [
        "The position favors me now.",
        "I have a decisive advantage.",
        "Your position is collapsing.",
        "A winning endgame approaches.",
        "Technique from here.",
      ],
      win: [
        "A well-fought victory.",
        "Your defense finally cracked.",
        "Superior positioning prevailed.",
        "An instructive game.",
        "Better luck next time.",
      ],
      lose: [
        "Impressive play. You earned it.",
        "You outmaneuvered me completely.",
        "A deserved victory.",
        "Strong endgame technique.",
        "I'll study this loss carefully.",
      ],
      draw: [
        "A hard-fought draw.",
        "Neither side could break through.",
        "Equally matched today.",
        "A balanced struggle.",
        "A fair result.",
      ],
    },
  },
  {
    id: "lei",
    name: "Lei",
    portrait: "/opponents/lei.png",
    personality: "Playful challenger",
    dialogue: {
      intro: [
        "Let's play something wild!",
        "Time for some tactics!",
        "I hope you brought your A-game!",
        "This is going to be fun!",
        "Ready to sacrifice some pieces?",
      ],
      playerMove: [
        "Ooh, that's spicy!",
        "Bold move! I like it!",
        "Interesting choice!",
        "You're going for it!",
        "That's aggressive!",
        "I see you!",
        "Nice development!",
        "Strong square control!",
      ],
      opponentMove: [
        "Watch this tactic!",
        "Here comes the pressure!",
        "My pieces are waking up!",
        "Let's complicate things!",
        "Time to counterattack!",
        "Boop! Your pawn is mine!",
        "Setting a little trap!",
        "This is going to be good!",
      ],
      capture: [
        "Got it! Delicious pawn!",
        "Snack time!",
        "Yum! Material gain!",
        "Nom nom! Free piece!",
        "That was satisfying!",
        "Trading into something better!",
        "Simplifying with style!",
      ],
      check: [
        "Check! Your king is in trouble!",
        "Hey, your king! Watch out!",
        "Danger! King under fire!",
        "Check! Where to now?",
        "Your king needs to run!",
      ],
      playerWin: [
        "You're on fire today!",
        "Wow, that's strong play!",
        "Great moves! Keep it up!",
        "You're crushing it!",
        "Impressive attack!",
      ],
      opponentWin: [
        "I see a winning path!",
        "Here it comes! The finish!",
        "My attack is connecting!",
        "Almost there! Hang on!",
        "This is going to be good!",
      ],
      win: [
        "GG! That was awesome!",
        "What a game! You nailed it!",
        "Rematch? I want another go!",
        "You played brilliantly!",
        "That was so much fun!",
      ],
      lose: [
        "Aww, nice one! You got me!",
        "Good game! Well played!",
        "That was a blast! Again?",
        "You really found the tactics!",
        "I'll get you next time!",
      ],
      draw: [
        "Draw? What a battle!",
        "Even Stevens! Close one!",
        "That was intense! Draw!",
        "Neither of us giving up!",
        "A thrilling draw!",
      ],
    },
  },
  {
    id: "yunjin",
    name: "Yunjin",
    portrait: "/opponents/yunjin.png",
    personality: "Calm thinker",
    dialogue: {
      intro: [
        "A thoughtful game awaits us.",
        "Let us begin with quiet focus.",
        "I observe and respond.",
        "Each move tells a story.",
        "The board is a canvas.",
      ],
      playerMove: [
        "A considered choice.",
        "Your position grows stronger.",
        "I see your long-term plan.",
        "Well thought through.",
        "A patient approach.",
        "Your structure is solid.",
        "Interesting piece coordination.",
        "You think several moves ahead.",
      ],
      opponentMove: [
        "A quiet improvement.",
        "Let me reposition gently.",
        "This square feels right.",
        "Restricting gradually.",
        "A subtle but important move.",
        "Preparing the pawn structure.",
        "My pieces find harmony.",
        "Patience is key.",
      ],
      capture: [
        "An exchange of value.",
        "The position shifts quietly.",
        "A necessary trade.",
        "Balancing the material.",
        "Simplifying toward clarity.",
        "Removing tension.",
        "The board breathes easier.",
      ],
      check: [
        "Check. A gentle warning.",
        "Your king is exposed.",
        "A quiet but sharp threat.",
        "Where will the king find safety?",
        "Forcing a response.",
      ],
      playerWin: [
        "You play with precision.",
        "A strong positional advantage.",
        "Your vision is clear.",
        "Impressive technique.",
        "You see the board deeply.",
      ],
      opponentWin: [
        "A subtle advantage grows.",
        "The position favors patience.",
        "My pieces find their places.",
        "A quiet winning technique.",
        "The endgame approaches.",
      ],
      win: [
        "A fine game. Well played.",
        "Your technique was strong.",
        "I enjoyed this battle.",
        "Until we meet again.",
        "A beautiful game of chess.",
      ],
      lose: [
        "Well done. A deserved win.",
        "Your play was inspiring.",
        "I learned from this game.",
        "A graceful victory.",
        "Until next time, friend.",
      ],
      draw: [
        "A balanced result.",
        "Equally matched today.",
        "A peaceful conclusion.",
        "Neither side yielded.",
        "A harmonious draw.",
      ],
    },
  },
];
