export const opponents = [
  {
    id: "giselle",
    name: "Giselle",
    portrait: "/opponents/giselle.png",
    personality: "Sharp strategist",
    dialogue: {
      intro: [
        "Let's begin.",
        "Ready when you are.",
        "I won't go easy.",
        "A good match awaits.",
        "Focus.",
      ],
      playerMove: [
        "Noted.",
        "A sound choice.",
        "I see your intent.",
        "Calculated.",
        "Accepted.",
      ],
      opponentMove: [
        "Observe.",
        "A precise move.",
        "Consider this.",
        "Strategic.",
        "My response.",
      ],
      capture: [
        "An expected trade.",
        "The board adjusts.",
        "Logical.",
        "A fair exchange.",
      ],
      check: [
        "Check.",
        "Your king requires attention.",
        "A direct challenge.",
      ],
      playerWin: [
        "Strong play.",
        "Your strategy is clear.",
        "Well executed.",
      ],
      opponentWin: [
        "A calculated advantage.",
        "The position favors me.",
        "Patience.",
      ],
      win: [
        "Well played.",
        "A fine game.",
        "You played well.",
        "Respectfully won.",
      ],
      lose: [
        "Well done.",
        "A worthy opponent.",
        "You earned this.",
        "Until we meet again.",
      ],
      draw: [
        "A balanced result.",
        "Equally matched.",
        "A fair outcome.",
      ],
    },
  },
  {
    id: "lei",
    name: "Lei",
    portrait: "/opponents/lei.png",
    personality: "Playful challenger",
    dialogue: {
      intro: [
        "Let's go!",
        "Ready to rumble!",
        "Game time!",
        "This will be fun!",
        "Bring it on!",
      ],
      playerMove: [
        "Ooh, spicy!",
        "Bold move!",
        "I like that!",
        "Interesting!",
        "Nice one!",
      ],
      opponentMove: [
        "Watch this!",
        "Here I come!",
        "My turn!",
        "Let's dance!",
        "Boop!",
      ],
      capture: [
        "Got it!",
        "Snack time!",
        "Yum!",
        "Delicious!",
        "Nom nom!",
      ],
      check: [
        "Check!",
        "Hey, your king!",
        "Watch out!",
        "Danger!",
      ],
      playerWin: [
        "You're on fire!",
        "Wow, strong!",
        "Great plays!",
        "Keep it up!",
      ],
      opponentWin: [
        "Sneaky sneaky!",
        "I see a path!",
        "Here it comes!",
        "Almost there!",
      ],
      win: [
        "GG!",
        "That was awesome!",
        "You nailed it!",
        "Rematch?",
      ],
      lose: [
        "Aww, nice one!",
        "You got me!",
        "Good game!",
        "That was fun!",
      ],
      draw: [
        "Draw? Nice!",
        "Even Stevens!",
        "Close one!",
      ],
    },
  },
  {
    id: "yunjin",
    name: "Yunjin",
    portrait: "/opponents/yunjin.png",
    personality: "Calm thinker",
    dialogue: {
      intro: [
        "Let us begin.",
        "A thoughtful game awaits.",
        "Ready.",
        "I observe and respond.",
        "Peaceful match ahead.",
      ],
      playerMove: [
        "Noted.",
        "A considered choice.",
        "I see your intent.",
        "Interesting approach.",
        "Well thought.",
      ],
      opponentMove: [
        "My turn.",
        "A quiet move.",
        "Let me consider.",
        "This feels right.",
        "Continuing gently.",
      ],
      capture: [
        "An exchange of value.",
        "The position shifts.",
        "A necessary trade.",
        "Balanced.",
      ],
      check: [
        "Check.",
        "Your king is exposed.",
        "A careful warning.",
      ],
      playerWin: [
        "You play with precision.",
        "Strong positioning.",
        "Impressive vision.",
      ],
      opponentWin: [
        "A subtle advantage.",
        "The position favors me.",
        "Patience pays off.",
      ],
      win: [
        "Well played.",
        "A fine match.",
        "You played well.",
        "Respect.",
      ],
      lose: [
        "Well done.",
        "A good game.",
        "You earned that.",
        "Until next time.",
      ],
      draw: [
        "A balanced result.",
        "Equally matched.",
        "A fair outcome.",
      ],
    },
  },
];
